[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[functions]
  external_node_modules = ["anthropic"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 